version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-server
    restart: always
    networks:
      - network
    volumes:
      - home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      TZ: "Asia/Seoul"
volumes:
   home:
networks:
   network:
      driver: bridge
